### ISSUE TITLE
We now have 2 sign up pages

### ISSUE THREAD

**Issue by erinmadisonanthony** [paircolumbus/pairs2#33]
Hey @TravisSperry I just realized that you created a sign up page prior to when Devise auto-created a sign up page, so I didn't address that in my latest push. Your page is at app/views/pages/sign_up.html.erb and the Devise-generated page is at app/views/devise/registrations/new.html.erb  I suspect it will mess up the Devise functionality if we don't stick with what Devise created. Do you think we could just update the Devise sign up page with the missing input fields from your other sign up page?

**Comment by TravisSperry** [comment]
It's not a problem that they both exist, but we should stick with one. I prefer moving things to controllers that are a better fit for what the pages actually do. Since it's likely we will create a suite of static pages, the sign up page being one, I vote to move away from the auto generated pages. But that's just me being picky. Thoughts?

**Comment by TravisSperry** [comment]
Disregard the previous comment. Since user creation is involved it makes sense to use the devise generated form.

**Comment by TravisSperry** [comment]
Removed in #34
